site_name = "Tw2-Tracker"
admin_password = "admin"

[ui]
ranking_page_items_per_page = 20
world_page_maximum_ranking_items = 10
world_page_maximum_last_conquests = 10

[sync]
static_share_expire_time = "90 days"
parallel_achievements_sync = 3
parallel_data_sync = 3

[sync.intervals]
data_all = "60 minutes"
achievements_all = "6 hours"
worlds = "3 hours"
clean_shares = "24 hours"

[database]
user = "postgres"
host = "127.0.0.1"
database = "tw2tracker"
password = "DATABASE_PASSWORD_HERE" # the password cannot be empty!
port = 5432

[puppeteer]
chromium_path = "/usr/bin/chromium"
headless = true
