site_name = "Tw2-Tracker"
admin_password = "admin"
ranking_items_per_page = 20
sync_data_all_parallel_syncs = 3
sync_achievements_all_parallel_syncs = 3

[sync]
interval_data_all = "30 */1 * * *"
interval_achievements_all = "0 */12 * * *"
interval_worlds = "10 */12 * * *"
interval_clean_shares = "0 */12 * * *"
static_share_expire_time = 129600

[database]
user = "postgres"
host = "127.0.0.1"
database = "tw2tracker"
password = "DATABASE_PASSWORD_HERE" # the password cannot be empty!
port = 5432

[puppeteer]
chromium_path = "/usr/bin/chromium"
headless = true
